# Dependencies
highlighter: rouge

# Permalinks
permalink:        pretty



# Setup
title:            Tom Starshak
tagline:          'A Personal Page'
description:      'Thoughts on ML, soccer, and other things.'
 #url:              http://tomstarshak.github.io
 baseurl:          /

 author:
   name:           'Tom Starshak
  # url:            https://twitter.com/mdo

paginate:         5

# Use the following plug-ins:
gems:
  - jekyll-paginate # The official Jekyll paginator.
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem.

