# Dependencies
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

# Permalinks
permalink:        pretty



# Setup
title:            Tom Starshak
tagline:          'A Personal Page'
description:      'Thoughts on ML, soccer, and other things.'
# url:              http://hyde.getpoole.com
# baseurl:          /

# author:
  # name:           'Tom Starshak
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TomStarshak
